version: '2'
services:
  firefox:
    container_name: selenium_firefox
    image: selenium/node-firefox:3.141.59-yttrium
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    logging:
      driver: none
    networks:
      - autotests

  chrome:
    container_name: selenium_chrome
    image: selenium/node-chrome:3.141.59-yttrium
    depends_on:
      - hub
    environment:
      HUB_HOST: selenium_hub
    logging:
      driver: none
    networks:
      - autotests

  hub:
    container_name: selenium_hub
    image: selenium/hub:3.141.59-yttrium
    logging:
      driver: none
    ports:
      - "4444:4444"
    networks:
      - autotests

  autotests:
    depends_on:
      - chrome
      - hub
      - firefox
    container_name: selenium_autotests
    build: .
    environment:
      - SELENIUM_HUB_HOST=selenium_hub
    ports:
      - "4446:8000"
    networks:
      - autotests
    command:
      - /bin/sh
      - -c
      - |
        pytest --headless=True --remote=True --alluredir=allure/results
        allure generate -o allure/report allure/results
        allure open allure/report -p 8000

networks:
  autotests:
    driver: bridge
