version: '2'
services:
  firefox:
    container_name: selenium_firefox
    image: selenium/node-firefox:3.141.59-yttrium
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    logging:
      driver: none
    ports:
      - "5558:5555"
    networks:
      - autotests

  chrome:
    container_name: selenium_chrome
    image: selenium/node-chrome:3.141.59-yttrium
    depends_on:
      - hub
    environment:
      HUB_HOST: selenium_hub
    logging:
      driver: none
    ports:
      - "5556:5555"
    networks:
      - autotests

  hub:
    container_name: selenium_hub
    image: selenium/hub:3.141.59-yttrium
    logging:
      driver: none
    ports:
      - "4444:4444"
    networks:
      - autotests


networks:
  autotests:
    driver: bridge
